### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by Vastrix** [Metalloriff/BetterDiscordPlugins#1]
Hey,  
  
Using the **birthday** one (because meh, why not :) and the **logger** (which I assume is early early alpha as it doesn't really work yet?)  

For the Birthday one tho, any chance you can use some sexy date-picker?
Or at least allow for a proper time format? :p (dd/mm/yyyy) (year as well, so it can tell how old he/she is)  
  
Just an idea tho ;)  
cheers o/

**Comment by Metalloriff** [comment]
I apologize for the 9 day late response, I didn't realize Github had this tab, lol.

The DIscordLogger does work, but the server logging feature is very buggy. The main features (logging and notifying when a server or friend is removed) work fine though.

I will look into having a date picker, and the choice to specify a year.

Thank you for the suggestion! 😃

**Comment by Vastrix** [comment]
You're very welcome! :)
