### ISSUE TITLE
[Bug] PinCollapsedChannels Not Working

### ISSUE THREAD

**Issue by Kederan** [Metalloriff/BetterDiscordPlugins#100]
**Which plugin is this about?**
PinCollapsedChannels v0.0.1

**Describe the Bug**
1. When you right click and select pin channels it does not do anything.
2. Sometimes the option to pin channel does not show up.

**To Reproduce**
I restarted the plugin multiple times. Refreshed my client and still get the bug.

**Expected Behavior**
Allows you to pin channels on collapsed categories, similar to if there was an unread message.

**Screenshots**
![2019-09-13_22-55-36](https://user-images.githubusercontent.com/19885815/64902696-f4535680-d679-11e9-99cd-3377c1c8bb94.gif)

**Discord Version**
Stable

**Comment by ardittristan** [comment]
@Kederan For me it worked again when I switched to a different theme. A makeshift solution I had before I switched theme was to add the channel id in the plugin settings and then reload discord.
