### ISSUE TITLE
Message Logger - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by Nixuge** [Metalloriff/BetterDiscordPlugins#103]
-Cannot click on MessagerLogger when right click
-Deleted messages don't appear red in chat
-Edited messages don't appear at all in chat
+Link dead, new link: https://github.com/Metalloriff/UnofficialBetterDiscordPlugins/blob/master/MessageLogger.plugin.js

**Comment by l0c4lh057** [comment]
It is recommended to use a new version made by another guy, delete the old one and install https://_lighty_.gitlab.io/bdstuff/plugins/MessageLoggerV2.plugin.js

**Comment by ZuranaSuki** [comment]
don't use message logger you will get banned for using it

**Comment by l0c4lh057** [comment]
nah, thats not true. as long as nobody reports you, discord won't ban you. that means, you shouldn't tell anybody you use it, but you dont automatically get banned for using it.
