### ISSUE TITLE
Message Logger - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by ossevi** [Metalloriff/BetterDiscordPlugins#104]
the link does not work

**Comment by l0c4lh057** [comment]
Download from [here](https://_lighty_.gitlab.io/bdstuff/plugins/MessageLoggerV2.plugin.js)

**Comment by ZuranaSuki** [comment]
don't use message logger you will get banned for using it

**Comment by l0c4lh057** [comment]
nah, thats not true. as long as nobody reports you, discord won't ban you. that means, you shouldn't tell anybody you use it, but you dont automatically get banned for using it.
