### ISSUE TITLE
Clap Clap plugin not working

### ISSUE THREAD

**Issue by 98otiss03** [Metalloriff/BetterDiscordPlugins#11]
superclap: and clapclap: do not change the spaces to clap emojis

**Comment by manskou** [comment]
also not ra:, b: and owo: seem to work, might be related to #8 ?

**Comment by Metalloriff** [comment]
Do they work now? I'm two weeks late, but that was a bug that happened from the Discord update, then I fixed it but only for a few commands apparently, then I fixed it for everything.

**Comment by manskou** [comment]
yeap they work as expected, thanks!

**Comment by Metalloriff** [comment]
👍
