### ISSUE TITLE
Mention Aliases not working

### ISSUE THREAD

**Issue by Entrodor** [Metalloriff/BetterDiscordPlugins#111]
using Discord stable, but mention aliases doesnt load and no error pops up
looking in discord console, i see this: 
![image](https://user-images.githubusercontent.com/22879622/67394572-2b5d4600-f5f0-11e9-87a0-5a68dd3df2c2.png)
ive tried disable then enable the plugin, reinstall of plugin, as well as restarting discord.. to no success

**Comment by l0c4lh057** [comment]
Metalloriff's version of MentionAliases is broken. You can use [Lighty's version](https://_lighty_.gitlab.io/bdstuff/?plugin=MentionAliases) instead.
