### ISSUE TITLE
[Bug] GuildCounter not working

### ISSUE THREAD

**Issue by ardittristan** [Metalloriff/BetterDiscordPlugins#114]
GuildCounter doesn't show up when started, and when you try to disable it again it can not be stopped. Tried loading the plugin with only library plugins active, and the same thing still happened.
![image](https://user-images.githubusercontent.com/42787508/68044225-30e51b00-fcd7-11e9-9fbb-13e84af695c8.png)

**Comment by DesertDog1178** [comment]
Same

**Comment by ardittristan** [comment]
![image](https://user-images.githubusercontent.com/42787508/72859148-1feaeb00-3cc3-11ea-8095-66af124378fe.png)
