### ISSUE TITLE
[Bug] User Birthdays not working

### ISSUE THREAD

**Issue by ardittristan** [Metalloriff/BetterDiscordPlugins#115]
User Birthdays doesn't show up when started, and when you try to disable it again it can not be stopped. Tried loading the plugin with only library plugins active, and the same thing still happened.
![image](https://user-images.githubusercontent.com/42787508/68044294-4fe3ad00-fcd7-11e9-91d3-c1918b11efef.png)

**Comment by DesertDog1178** [comment]
Same
