### ISSUE TITLE
Layout of DetailedServerTooltips broke with latest Discord update

### ISSUE THREAD

**Issue by Huddlect** [Metalloriff/BetterDiscordPlugins#116]
The tooltip sometimes appears too far down right and sometimes it doesn't appear at all

**Comment by ggtylerr** [comment]
Just to add to this, sometimes it appears like so:
![image](https://user-images.githubusercontent.com/28498877/68929653-a1615280-0741-11ea-9dba-336f3283aaec.png)
For servers that don't have an server icon:
![image](https://user-images.githubusercontent.com/28498877/68929839-f8672780-0741-11ea-896f-67e0260df6a0.png)
And for servers all the way at the bottom of the server list (picture taken in a portrait monitor, on landscape it's completely offscreen):
![image](https://user-images.githubusercontent.com/28498877/68930046-6ad80780-0742-11ea-92fe-5c435609701f.png)

**Comment by Metalloriff** [comment]
Fixed in the latest update. Thank you for reporting.

**Comment by Huddlect** [comment]
Now it mostly doesn't appear at all. However if it appears the layout is correct.

**Comment by Huddlect** [comment]
The tooltip only appears when moving the mouse from the channels section to a server. It doesn't appear when moving the mouse from one server to another.
