### ISSUE TITLE
Save-To Failing to save files

### ISSUE THREAD

**Issue by sinnx3** [Metalloriff/BetterDiscordPlugins#12]
![oexr2sy](https://user-images.githubusercontent.com/3137441/43623903-7826000a-96a9-11e8-8dc8-174d8feb7ad7.png)
Doesn't matter what it is or what the plugin set to (from what I've experienced)
**Version:** Save To v0.5.6 by Metalloriff

**Comment by Metalloriff** [comment]
Are you saving files that can't be saved? Have you tried things like images or other files?
