### ISSUE TITLE
[Enhancement] DetailedServerTooltips: Show if a server is verified

### ISSUE THREAD

**Issue by Huddlect** [Metalloriff/BetterDiscordPlugins#121]
like the default tooltip does. Could look similar to the indicator for partnered servers.

**Comment by l0c4lh057** [comment]
it should show that information. at least if you are talking about partnered servers, afaik there are only partnered servers but not verified servers as you said.
https://github.com/Metalloriff/BetterDiscordPlugins/blob/beab1381af7f96cf3989c1968ab9d9a5d2af6660/DetailedServerTooltips.plugin.js#L278

**Comment by Huddlect** [comment]
https://discordapp.com/verification
