### ISSUE TITLE
Share: Not Working; Uncaught TypeError

### ISSUE THREAD

**Issue by wxMichael** [Metalloriff/BetterDiscordPlugins#13]
When I click on a channel to share an image, nothing happens.

Console:
VM408:577 Uncaught TypeError: Cannot read property 'scrollTop' of undefined
    at ShareButton.sendMessage (<anonymous>:577:173)
    at HTMLDivElement.channelClickEvent (<anonymous>:468:18)
sendMessage @ VM408:577
channelClickEvent @ VM408:468

**Comment by wxMichael** [comment]
The messages class is now named messages-3amgkR.

**Comment by Metalloriff** [comment]
Fixed, thanks.
