### ISSUE TITLE
[BetterEmoteSizes] EMotes have incorrect z-level

### ISSUE THREAD

**Issue by dexman545** [Metalloriff/BetterDiscordPlugins#143]
![image](https://user-images.githubusercontent.com/4873274/73905730-5baeb480-486e-11ea-9ac9-38b04f50210a.png)
They appear to clip under other messages

**Comment by ajloveslily14** [comment]
I've found a solution to this, to use it however you need to go to settings -> bandaged bd -> settings and enable "normalize classes" then in custom css put 

```
.da-contents {
    overflow: visible !important;
}
```

**Comment by dexman545** [comment]
@ajloveslily14 unfortunately that doesn't seem to work for me

**Comment by ajloveslily14** [comment]
Are you using the light theme? Also are you using bandages bd?  I'm not sure if discord needs to be restarted before it takes effect

**Comment by dexman545** [comment]
Dark theme, bandaged bd
it worked for reactions, not normal emojis

**Comment by ajloveslily14** [comment]
nice. I tried fiddling with the code for the plugin but it seems to only be targeted at those who use the cozy theme and not the compact one.
