### ISSUE TITLE
[TransitioningBackgrounds] Suggestion for improvement

### ISSUE THREAD

**Issue by just-Addict** [Metalloriff/BetterDiscordPlugins#158]
The old version showed the top of the image as background in the inputs. While this was nice it doesn't make it really helpful to identify the image. At the time I sent you a modified version that showed the images as a contact sheet. 

This latest version however doesn't even show that top part anymore so now it's a total blind guess which background goes with which input. Once again I've modified it to again show images as a contact sheet.

I added the below function
```
	showImages() {
		setTimeout(() => {
		let existing = document.querySelectorAll('.neato-setting-array-items .neato-setting');
		for (let i = 0; i < existing.length; i++) {
			let imgInput = existing[i].querySelector('.neato-textfield');
				imgInput.setAttribute('style','width:192px;height:108px;background-image: url("' + imgInput.value + '");background-size: cover;');
		}
		},500);	
	}
```

and inserted calls to this function in `getSettingsPanel()` before the return statement, and in `saveSettings()` as last statement. 

I've attached a partial screenshot to view how this looks.
![image](https://user-images.githubusercontent.com/19715616/80891307-748b0280-8cc3-11ea-9c88-0d1a2d48fb9b.png)
I hope you can agree that this is far more usable than just mere links.

I also wanted to make it so adding images would show the new input still as a line but that would require more rewriting than I cared for, seeing as it isn't my own plugin and the previous modification totally got ignored. 

Also please consider re-adding the context menu items to add images found in the various discord servers/channels one might be a member of.

PS. I didn't create a PR because that would require forking. And keeping track of whatever changes you might make to plugins so I could keep the fork in sync would be too much work for my taste.

**Comment by just-Addict** [comment]
This also required some CSS additions/changes. 
```
			.neato-setting-array-items > .neato-setting { display: inline-block; }
			.neato-setting-array .neato-array-remove-button { 
				position: relative;
				display: inline-block;
				float: left!important; 
				font-size: 24px!important; }
			.neato-setting-array .neato-setting:hover .neato-array-remove-button { width: 0!important; }
```

**Comment by just-Addict** [comment]
@Metalloriff Any chance the above will make it into the release version? Like I said above, I didn't make a PR because I use less than a handful of your plugins, so it's too much work keeping a fork of your repo in sync with any updates you may add.

**Comment by Metalloriff** [comment]
I apologize for the super late response, I don't check my GitHub often as I don't receive notifications. The functionality of TB has been changed to use a folder instead of image links now, although I really do like your idea! I will consider something like that if I re-add an option to use image links.
