### ISSUE TITLE
AvatarIconViewer No longer working

### ISSUE THREAD

**Issue by espionage1337** [Metalloriff/BetterDiscordPlugins#159]
No longer working :c

**Comment by KingFC01** [comment]
Same here after the last update.

**Comment by Phosphorjr** [comment]
same, isnt working

**Comment by JohnWeak1** [comment]
same here and it's because discord updated their context menu into a new one that nobody actually wanted ending up in many context menu based plugins to break

**Comment by Phosphorjr** [comment]
looks like its time to update this

**Comment by yorik100** [comment]
Broken again
