### ISSUE TITLE
View Guild Relationships broken

### ISSUE THREAD

**Issue by Teslahaha** [Metalloriff/BetterDiscordPlugins#161]
The View Guild Relationships plugin has not been working for some time. The button in the context menu is missing. I think the last Discord update broke it.

**Comment by bobross135** [comment]
+1

**Comment by DesertDog1178** [comment]
+2

**Comment by RickeyJLancaster** [comment]
+3

**Comment by hhdhwuus** [comment]
+4

**Comment by AyalX** [comment]
+5

**Comment by Technetium1** [comment]
+6

**Comment by DesertDog1178** [comment]
He has stopped all support of Discord and Better Discord, he moved onto Gilded, so no fixes unless someone else does it.
