### ISSUE TITLE
Detailed Server Tooltips - Doesnt Work

### ISSUE THREAD

**Issue by Mishelovka** [Metalloriff/BetterDiscordPlugins#162]
Plugin Detailed Server Tooltips doesnt work.

**Comment by AyalX** [comment]
Yeah it doesn't, discord did a UI update and in-order for this plugin to work the developer must update his plugin.

**Comment by dudefoxlive** [comment]
Ok so I'm not going crazy. Was wondering why it was not working.

**Comment by skaneprime** [comment]
Dev of plugin didn't fix yet, did he?

**Comment by Mishelovka** [comment]
It’s still broken 

Отправлено с iPhone

**Comment by AyalX** [comment]
Is it possible to fix?

**Comment by Mishelovka** [comment]
I am not developer. I don’t know 

Отправлено с iPhone

**Comment by dudefoxlive** [comment]
I would like this plugin fixed as it was helpful.

**Comment by SadHurts** [comment]
when will this get fixed :(
