### ISSUE TITLE
PinCollapsedChannels.plugin.js

### ISSUE THREAD

**Issue by Mephistou** [Metalloriff/BetterDiscordPlugins#163]
Not working right. There's no option to pin or unpin when you right-click the channel.
All you can do is just copy channel ID code and go to plugins and paste it there inside that plugin.

i hope you can fix.

**Comment by PikminRed** [comment]
I am still seeing this issue as well.

**Comment by yShyboy** [comment]
True, I missed this plugin.

**Comment by ImNotIfDumb** [comment]
Is there any plan to fix this? I can't even pin them by copying the ID

**Comment by theS1LV3R** [comment]
The plugin uses a method that isn't available (container.getElementsByClassName). Don't know how to fix it unfortunately :/

```
VM554 C:\Users\me\AppData\Roaming\BetterDiscord\plugins\PinCollapsedChannels.plugin.js:20 PinCollapsedChannels fatal error, plugin could not be started! TypeError: container.getElementsByClassName is not a function
    at Object.tryCreateToastContainer (NeatoBurritoLibrary.js:2580)
    at Object.showToast (NeatoBurritoLibrary.js:2602)
    at Object.onPluginLoaded (NeatoBurritoLibrary.js:1761)
    at PinCollapsedChannels.onLibLoaded (VM554 C:\Users\me\AppData\Roaming\BetterDiscord\plugins\PinCollapsedChannels.plugin.js:76)
    at libLoadedEvent (VM554 C:\Users\me\AppData\Roaming\BetterDiscord\plugins\PinCollapsedChannels.plugin.js:19)
    at r (c8bb8d7d5941a98de86e.js:16)
```

**Comment by SeleneBathory** [comment]
Not working at all since the new BD version. Same question, there is plan to fix it ? It's really a great plugin.

**Comment by Firecul** [comment]
I guess that is a no then 🙁

**Comment by Metalloriff** [comment]
I closed all issues and made an announcement in the issues. There were over 70 issues that I'd missed, and didn't feel like filtering through all of those. I've been looking for a way to fix the plugin but discord screwed with their modules, and I can't seem to find the one they're using to keep channels from collapsing.

**Comment by Metalloriff** [comment]
I apologize for the confusion. I'm trying to actually keep up with any new issues from now.
