### ISSUE TITLE
DoubleClickVoiceChannels doesn't work anymore

### ISSUE THREAD

**Issue by JohnWeak1** [Metalloriff/BetterDiscordPlugins#166]
it just doesn't work

**Comment by ochen1** [comment]
Specifically, this is the error logged in the console.

This same error appears to be happening on all plugins, rendering all of them useless.

I assume that this is a problem with the NeatoBurritoLibrary?

Is this problem just for some people, or how can it be fixed otherwise?

```
93ac480ac929bccd76ed.js:16 Uncaught TypeError: temp[className].split is not a function
    at Object.getClass (NeatoBurritoLibrary.js:2358)
    at GuildAndFriendRemovalAlerts.checkGuilds (~/.config/Lightcord_BD/plugins/GuildAndFriendRemovalAlerts.plugin.js:232)
    at ~/.config/Lightcord_BD/plugins/GuildAndFriendRemovalAlerts.plugin.js:116
    at r (93ac480ac929bccd76ed.js:16)
```

**Comment by Glaived** [comment]
https://github.com/Metalloriff/BetterDiscordPlugins/pull/173
