### ISSUE TITLE
Autocorrect v2.0.1 causing multiple messages

### ISSUE THREAD

**Issue by Bilibox** [Metalloriff/BetterDiscordPlugins#175]
After a while of having the AutoCorrect plugin active. it will start sending duplicate messages when you hit enter instead of just 1. Upon disabling the plugin the issue disappears. Re-enabling after disabling will have a short reprieve until the issue pops up again.

Turning "Auto Punctuate" off does not fix this

"Patcher.instead(DiscordModules.MessageActions, "sendMessage", (_, args, sendMessage) =>" is what is sending the message twice. But something else is creating a duplicate message

**Comment by Metalloriff** [comment]
I've heard many people reporting this but haven't had it happen myself yet. Do you have any idea how to re-produce it?

**Comment by Bilibox** [comment]
Usually on start up it will happen. It didn't happen this time for some reason and I haven't found any way to reproduce it other than waiting until it starts happening.

I'll test and report back when it happens again and check if there's plugin compatibility issue.

Here's some info of what I have set up:
Canary 66167 (eab6c86)
BBD 0.3.5
Host 0.0.272
Injector 0.6.2
Windows 10 64-Bit (10.0.19041) 

Plugin JS files List:
0PluginLibrary.plugin.js
1lib_discord_internals.plugin.js
1XenoLib.plugin.js
AccountDetailsPlus.plugin.js
AlwaysMentionEveryone.plugin.js
AutoCorrect.plugin.js
AutoPlayGifs.plugin.js
BadgesEverywhere.plugin.js
BetterFolders.plugin.js
BetterFormattingRedux.plugin.js
BetterFriendList.plugin.js
BetterImageViewer.plugin.js
BetterNsfwTag.plugin.js
BetterReplyer.plugin.js
BetterSearchPage.plugin.js
BetterTypingUsers.plugin.js
BetterUnavailableGuilds.plugin.js
BlurNSFW.plugin.js
ChannelPopouts.plugin.js
ChannelTabs.plugin.js
CharCounter.plugin.js
ChatUserIDsRedux.plugin.js
ColorSighted.plugin.js
CompleteTimestamps.plugin.js
CopyRawMessage.plugin.js
CrashRecovery.plugin.js
CreationDate.plugin.js
CustomQuoter.plugin.js
dateViewer.plugin.js
DetailedServerTooltips.plugin.js
DiscordCakeDay.plugin.js
discordexperiments.plugin.js
DiscordFreeEmojis.plugin.js
DisplayLargeMessages.plugin.js
DoNotTrack.plugin.js
GameActivityToggle.plugin.js
GoogleTranslateOption.plugin.js
GuildAndFriendRemovalAlerts.plugin.js
HideDisabledEmojis.plugin.js
ImageToClipboard.plugin.js
ImageUtilities.plugin.js
InAppNotifications.plugin.js
JoinedAtDate.plugin.js
LastMessageDate.plugin.js
LineNumbersRedux.plugin.js
LinkChannels.plugin.js
MobileForAll.plugin.js
OnlineFriendCount.plugin.js
OpenLinksInDiscordV2.plugin.js
OwnerTag.plugin.js
PermissionsViewer.plugin.js
PinDMs.plugin.js
PluginRepo.plugin.js
QuickMuteChannels.plugin.js
ReactionImages.plugin.js
RevealAllSpoilersOption.plugin.js
RoleMembers.plugin.js
SaveToRedux.plugin.js
SendLargeMessages.plugin.js
ServerCounter.plugin.js
ShareButton.plugin.js
SilentTyping.plugin.js
StatusEverywhere.plugin.js
SteamProfileLink.plugin.js
ThemeRepo.plugin.js
TypingIndicator.plugin.js
UnreadBadgesRedux.plugin.js
UnreadCountBadges.plugin.js
VoiceUsersCounter.plugin.js
