### ISSUE TITLE
Autocorrect: Triple message sending

### ISSUE THREAD

**Issue by ToothyDev** [Metalloriff/BetterDiscordPlugins#185]
As far as I saw it till now, on the very first start of Discord, autocorrect will send every sent message 3 times total. A reload fixes this, I didn't try a normal restart yet, but it sure is annoying to always having to reload before not spamming the channel

**Comment by Bilibox** [comment]
Hi @Chosen-Fate I have an issue about this open here https://github.com/Metalloriff/BetterDiscordPlugins/issues/175
Though my issue is for double messages it's odd that it's different for you. Hopefully the dev will be able to fix this!
