### ISSUE TITLE
VoiceChatNotifications doesn't seem to work at all

### ISSUE THREAD

**Issue by BlackWolfWoof** [Metalloriff/BetterDiscordPlugins#188]
The plugin is enabled and not creating any errors in the console and i made sure that every switch is set to on in the settings and that i am not on do not disturb but it is still not creating notifications. 
I am now using the old version (v3.0.0) again and the old one seems to be working fine.

**Comment by Xetaxheb** [comment]
3.0.0 doesn't seem to work even on an install with no other non-required plugins
