### ISSUE TITLE
NeatoBurritoLibrary/CustomJS Settings Unable To Load

### ISSUE THREAD

**Issue by Boii1** [Metalloriff/BetterDiscordPlugins#191]
3a4593111609629ff1e2.js:16 Uncaught TypeError: Cannot read property 'appendChild' of null
    at Object.pushElement (NeatoBurritoLibrary.js:1098)
    at C:\Users\User\AppData\Roaming\BetterDiscord\plugins\CustomJs.plugin.js:44
    at r (3a4593111609629ff1e2.js:16)

**Comment by Metalloriff** [comment]
NeatoBurritoLibrary is deprecated, and all of the plugins using it will either be rewritten using a different lib in time, or deprecated as well.
