### ISSUE TITLE
DoubleClickVoiceChannels not working on latest stable

### ISSUE THREAD

**Issue by cmd430** [Metalloriff/BetterDiscordPlugins#193]

**Comment by cmd430** [comment]
the previous fix is no longer working

**Comment by Metalloriff** [comment]
It's fixed again, sorry about that, don't check my GH issues often. I need to setup notifications.

Thank you for notifying me!

**Comment by cmd430** [comment]
@Metalloriff This update doesnt fix the issue for me i get the Warning `DoubleClickVoiceChannel: Failed to get nested props!`, however i fixed it on my end by changing lines `82` and `85` to the following:

Line 82
```js
const children = Utilities.getNestedProp(el, "props.children.props.children.0.props.children.props.children");
```
becomes
```js
const children = Utilities.getNestedProp(el, "props.children.0.props.children.props.children");
```


Line 85
```js
el.props.children.props.children[0].props.children.props.children = () => {
```
becomes
```js
el.props.children[0].props.children.props.children = () => {
```
