### ISSUE TITLE
Two GuildAndFriendRemovalAlerts feature suggestions that would make it so much better.

### ISSUE THREAD

**Issue by connect192168** [Metalloriff/BetterDiscordPlugins#196]
Suggestion 1:
**Friend kicked/banned/left the guild**
When a friend gets kicked/banned or leaves a guild you are in, the plugin shows the removed guilds popup with the users tag (username+discriminator) and the guild they are no longer in.
Suggestion 2:
**Logging displayed data**
A persistent log of the guild kick/ban/leaves,server deletions and friend removals that is viewable via a button.
e.g. if you're in the middle of something and click off the popup to make it disappear, you can come back later, open the log, and see the information that was previously displayed (and when it happened).

**Comment by DesertDog1178** [comment]
It sounds super stalkery, but it would be interesting to see in action and how it is used.

**Comment by connect192168** [comment]
Now I feel the need to justify the features lol

1. Friend left/kicked/banned:
A friend of mine just generally hung out with me in a particular discord server.
They got banned from a server for no reason (just a mod abusing) one day.
They weren't online much and for various reasons they don't read their DMs (and they didn't challenge the ban for whatever reason, idk).
I bumped into them a few months later in another discord and found out what happened.
I approached the staff team and the ban was rescinded.
With the proposed feature, I would have known about the situation sooner and if I'd know about it, I would have inquired as to why they got banned.

To be fair, this info is already made available by vanilla discord, you can look at the mutual servers that you and **any** user shares.
This feature would just make you more aware of when this information changes for friends, as this feature would cover you losing a mutual server with a friend, not gaining a mutual server with a friend.
IMO, this feature would be slightly stalkerish if not for the fact that both sides have to agree for you to friend a user.
The proposed feature would be automating you looking at your friends list and noting if the mutual servers between you and your friends have decreases.
Vanilla discord allows you to view mutual servers with anyone. Having this feature work on a user-defined list would be a bit stalkery and make it open to abuse.

2. Logs:
Sometimes I'm in the middle of something and I click off when the popup for this plugin shows up because I'm focused on what I'm doing and get annoyed that it got in the way.
Once I've clicked off to make it go away, I cannot go back and see what it said or when, so the plugin becomes pointless to have at that point.

**Comment by DesertDog1178** [comment]
You might have trouble, he has left discord entirely though.
![unknown (1)](https://user-images.githubusercontent.com/29591643/113861513-26e10a80-975c-11eb-9f98-b97a04f1e2eb.png)
