### ISSUE TITLE
VOICECHATPANEL plugin crashes discord when clicking on the "open audio graph" button

### ISSUE THREAD

**Issue by jack652** [Metalloriff/BetterDiscordPlugins#201]
happens on stable canary and ptb discord
crash recovery plugin shows this: 
![image](https://user-images.githubusercontent.com/48365199/111525224-a2532b80-875d-11eb-9cd0-a722f5d60506.png)

**Comment by cytsai1008** [comment]
Same On Me
Error Log:
Prettified stacktraces, stack:
 TypeError: getVoiceStates(...).filter is not a function
    at \VoiceChatPanel.plugin.js:325:41 
Component stack:
     in ModalLayer
    in TransitionGroup
    in Modals
    in ModalProvider
    in LayerProvider
    in AppLayerProvider
    in FocusRingScope
    in ErrorBoundary
