### ISSUE TITLE
GuildAndFriendRemovalAlerts spamming with a friend removal modal

### ISSUE THREAD

**Issue by whamer100** [Metalloriff/BetterDiscordPlugins#206]
Not sure what is causing it, but someone removed me, and every time i click off the modal, it pops back up with the same removal message.

Looking in console, its giving me this error every couple seconds
![image](https://user-images.githubusercontent.com/10352720/116965826-9830b200-ac63-11eb-8213-5512e3bd6baf.png)

**Comment by whamer100** [comment]
Restarting my client fixes the issue temporarily, I assume the looping will start again once someone unfriends.

**Comment by Mephistou** [comment]
To me restarting don't help, it keeps spamming still non stop

**Comment by whamer100** [comment]
try disabling the plugin, then restart and re-enable it? might temporarily solve the issue

**Comment by Kyr4l** [comment]
same problem here

**Comment by John4266** [comment]
I have the same issue.
This also applies to guilds.

**Comment by Nanofaux** [comment]
same issue here

**Comment by InFlamesGO** [comment]
same here
