### ISSUE TITLE
DoubleClickVoiceChannels Causes User Settings Lag

### ISSUE THREAD

**Issue by Vexadros** [Metalloriff/BetterDiscordPlugins#209]
The plugin causes tons of lag when opening and closing the "user settings" tab after a fresh launch and without opening any servers.

Steps to reproduce:
1. Start discord from a fresh launch
2. Don't view any servers
3. Open the user settings menu

**Comment by Auvere** [comment]
This had been driving me for quite awhile and was able to pin down to this plugin. Disabling the plugin didn't fix and it required a reinstall of BD. It looks like it has wait events according to the performance profiler.

**Comment by nyuszika7h** [comment]
Why was this closed? This is still an issue, reinstalling BD did not fix it. Only disabling the plugin does.

**Comment by Metalloriff** [comment]
@nyuszika7h https://github.com/Metalloriff/BetterDiscordPlugins/issues/224
