### ISSUE TITLE
GuildAndFriendRemovalAlerts "Could Not Be Constructed"

### ISSUE THREAD

**Issue by ShadowKamokezi** [Metalloriff/BetterDiscordPlugins#212]
alright so i load up BD with everything and it gives me this addon error and nothing else. this has worked perfectly fine with all my other addons/plugins so i dont know why this is happening now

GuildAndFriendRemovalAlerts: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:229093)
    at Object.loadAddon (<anonymous>:4:191125)
    at Object.loadAddon (<anonymous>:4:228205)
    at Object.loadAllAddons (<anonymous>:4:193377)
    at Object.initialize (<anonymous>:4:188055)
    at Object.initialize (<anonymous>:4:227415)
    at Object.startup (<anonymous>:4:286689)

**Comment by Nanofaux** [comment]
Same here

**Comment by PatrickSantoZZ** [comment]
jup same here.

**Comment by NicciZar** [comment]
For me It also says <anonymous>

```
GuildAndFriendRemovalAlerts: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:229093)
    at Object.loadAddon (<anonymous>:4:191125)
    at Object.loadAddon (<anonymous>:4:228205)
    at Object.loadAllAddons (<anonymous>:4:193377)
    at Object.initialize (<anonymous>:4:188055)
    at Object.initialize (<anonymous>:4:227415)
    at Object.startup (<anonymous>:4:286689)
```

**Comment by onej27** [comment]
same here

**Comment by InFlamesGO** [comment]
same here

**Comment by ashergz** [comment]
Same. please fix

**Comment by RealHours** [comment]
![image](https://user-images.githubusercontent.com/44280562/121431841-2a009e80-c937-11eb-9e7b-3699b001e227.png)
Same issue here.

**Comment by ZachFett** [comment]
ViewGuildRelationships is also unfortunately giving the same error.

**Comment by Ash3781** [comment]
> alright so i load up BD with everything and it gives me this addon error and nothing else. this has worked perfectly fine with all my other addons/plugins so i dont know why this is happening now
> 
> GuildAndFriendRemovalAlerts: Could not be constructed.
> at Object.initializeAddon (:4:229093)
> at Object.loadAddon (:4:191125)
> at Object.loadAddon (:4:228205)
> at Object.loadAllAddons (:4:193377)
> at Object.initialize (:4:188055)
> at Object.initialize (:4:227415)
> at Object.startup (:4:286689)

same here 
![2021-06-11_21-39_1](https://user-images.githubusercontent.com/37660156/121742136-f6687480-caee-11eb-9ce0-dfe02116952a.png)

**Comment by BlueStarBRS** [comment]
same here

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/121933734-bb607e00-cd46-11eb-8837-9a7e81353469.png)

**Comment by QuentinMcCarthy** [comment]
I am unfortunately getting the same issue, and have been getting it for a while now. I redownloaded the plugin from this repo and the issue persists. It needs a good lookin' at.

**Comment by insanityanimations** [comment]
Same issue, please fix soon?

**Comment by NicciZar** [comment]
Hello Guys,
Please try the new version the Author uploaded on their website. For me its working again

https://metalloriff.github.io/toms-discord-stuff/#/

just overwrite the old plugin file and restart discord!

**Comment by xerus6** [comment]
same here..
![image](https://user-images.githubusercontent.com/45909555/122019370-9a864000-cdbb-11eb-95b5-8d6c210bfbc3.png)

**Comment by xerus6** [comment]
The plugin has been updated, re download it for toms website.

**Comment by mutageneral** [comment]
> Please try the new version the Author uploaded on their website.

> The plugin has been updated, re download it from toms website.

did that and got this error:

```
GuildAndFriendRemovalAlerts: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:229093)
    at Object.loadAddon (<anonymous>:4:191125)
    at Object.loadAddon (<anonymous>:4:228205)
    at FSWatcher.<anonymous> (<anonymous>:4:189109)
```

seems like the exact same error as @BlueStarBRS but a different one as every one else before who showed the error before. I guess the update changed how the plugin crashes, but it fixed it for some people.

**Comment by mutageneral** [comment]
okay I got an update today for the rewrite of the add-on, everything seems fixed.

**Comment by alazymeme** [comment]
also having issues here when downloading from the Plugin Repo:
```
GuildAndFriendRemovalAlerts: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:229093)
    at Object.loadAddon (<anonymous>:4:191125)
    at Object.loadAddon (<anonymous>:4:228205)
    at FSWatcher.<anonymous> (<anonymous>:4:189109)
```

**Comment by YehnBeep** [comment]
I tried redownloading the plugin and I get this error:

GuildAndFriendRemovalAlerts: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:229093)
    at Object.loadAddon (<anonymous>:4:191125)
    at Object.loadAddon (<anonymous>:4:228205)
    at FSWatcher.<anonymous> (<anonymous>:4:189109)

**Comment by TanzaKnight** [comment]
Downloaded from the website and this still hasn't been fixed, Same error as the others.
