### ISSUE TITLE
MessageLogger: Compact mode support

### ISSUE THREAD

**Issue by binn** [Metalloriff/BetterDiscordPlugins#22]
![image](https://user-images.githubusercontent.com/25821642/51782734-91697b00-20fb-11e9-908c-49c96783c6f6.png)

![image](https://user-images.githubusercontent.com/25821642/51782737-962e2f00-20fb-11e9-8cf6-5218930c4bf9.png)

This is almost unusable on compact mode. I think a quick css fix could give compact mode support; thank you.

**Comment by Metalloriff** [comment]
Fixed in the latest update. Thank you for letting me know.
