### ISSUE TITLE
GuildAndFriendRemovalAlerts wrong source and multiple popups

### ISSUE THREAD

**Issue by Eden333** [Metalloriff/BetterDiscordPlugins#227]
When clicking on the plugins source, it leads to an old link (404)
and
When someone is removing you as friend, the popup keeps appearing until discord is restarted

**Comment by Metalloriff** [comment]
The popups can be fixed by deleting your config.json and restarting. I haven't been able to reproduce this, and therefore can't fix it otherwise. My guess is a conflict with the old version when I tried to support the old config files.

**Comment by Eden333** [comment]
> The popups can be fixed by deleting your config.json and restarting. I haven't been able to reproduce this, and therefore can't fix it otherwise. My guess is a conflict with the old version when I tried to support the old config files.

I could have sworn that I had done that in the past and it wouldn't fix it, but I have done it now and works perfectly fine again, thanks!
