### ISSUE TITLE
DoubleClickVoiceChannels Causes User Settings Lag

### ISSUE THREAD

**Issue by Vexadros** [Metalloriff/BetterDiscordPlugins#234]
The plugin causes tons of lag when opening and closing the "user settings" menu if you haven't visually encountered any voice channel. The lag also occurs with toast notifications, an easy example is when updating plugins.

Steps to reproduce:

1. Start discord from a fresh launch
2. Don't view any servers with a voice channel
3. Open the user settings menu

**Comment by QbDesu** [comment]
You can try https://github.com/QbDesu/BetterDiscordAddons/tree/potato/Plugins/DoubleClickVoiceChannels instead. Metalloriff's DoubleClickVoiceChannels hasn't been updated in over a year and probably won't be updated anytime soon.

**Comment by Vexadros** [comment]
@QbDesu Thank you so much
