### ISSUE TITLE
What the fuck (opening in browser)

### ISSUE THREAD

**Issue by lynrayy** [Metalloriff/BetterDiscordPlugins#238]
Why the fuck this plugin now opens icon in the browser? It is very shitty solution! 🤢
Make it open images inside discord again

**Comment by lynrayy** [comment]
Im about AvatarIconViewer.plugin

**Comment by Metalloriff** [comment]
Fix it yourself then. I do not have the time or energy to spend several hours figuring out what Discord broke with the modals system. If you'd read the original post, I wouldn't have to explain this.

**Comment by Metalloriff** [comment]
*It is a temporary solution. When other developers figure out what they broke with modals, I will fix it.

**Comment by lynrayy** [comment]
> It is a temporary solution.
Ok thanks for response

**Comment by lynrayy** [comment]
...quotes are broken on github
