### ISSUE TITLE
Discord Logger attempts to load a non-existent library plugin.

### ISSUE THREAD

**Issue by drogga** [Metalloriff/BetterDiscordPlugins#26]
GET https://mwittrien.github.io/BetterDiscordAddons/Plugins/BDfunctionsDevilBro.js net::ERR_ABORTED 404 shows in the console.

**Comment by silent** [comment]
DiscordLogger is no longer supported.

**Comment by Metalloriff** [comment]
MessageLogger is the closest to it that's still updated. It doesn't log server and friend removals, but GuildAndFriendRemovalAlerts does that, MessageLogger logs deleted and edited messages.
