### ISSUE TITLE
Infinite Updating Issue For Open Links In Discord

### ISSUE THREAD

**Issue by Benzeel** [Metalloriff/BetterDiscordPlugins#30]
SO better discord keeps saying "The Following Plugins Have Updates: OpenLinksInDiscord"
and when I click it it says it updated but the prompt still stays there. And The Prompt For The Other Plugins Updates Go away And Update When I Click Them But Not This One

it Keeps Saying it replaced the plugin with version 1.1.4 Even Know It didn't so I had to Manually Update It From 1.1.2

REE

**Comment by Benzeel** [comment]
it just kept doing that and it got annoying Btw  Even Know I Manually Updated It And Shut Down And Reopened Discord It Still Says It Has To Update It To A Version I Already Have.

**Comment by Metalloriff** [comment]
You've tried manually uninstalling the plugin and reinstalling it?
