### ISSUE TITLE
Server's title won't disappear 

### ISSUE THREAD

**Issue by egozi44** [Metalloriff/BetterDiscordPlugins#35]
So after one of the few recent discord updates, I start getting this annoying bug, it won't when I turn DetailedServerTooltips off

https://user-images.githubusercontent.com/14190834/55448936-5a6b8600-55d2-11e9-901b-63edcdb83644.PNG

Can you fix it?

**Comment by Metalloriff** [comment]
Fixed in the latest update. Thank you!
