### ISSUE TITLE
Message Logger - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by rinzler3161** [Metalloriff/BetterDiscordPlugins#41]
seems im the only one but its not working at all for me, the plugin loads then does nothing
these are the errors my console shows 
https://gyazo.com/3c2bbbc9b2da7b54611ef7917baecfb8

**Comment by Ceanko** [comment]
I've been having this issue for a while now. Something's wrong with the data initialization.

![image](https://user-images.githubusercontent.com/7291781/56864492-55c4a280-69c3-11e9-9944-ca9952003748.png)

**Comment by Ceanko** [comment]
Although not specifically related to this issue, I've been getting more issues with NeatoLib.
`localUser` is also undefined.

![image](https://user-images.githubusercontent.com/7291781/56864553-02068900-69c4-11e9-8332-1cec4a1d4f3e.png)
