### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by TheBlackGhost77** [Metalloriff/BetterDiscordPlugins#42]
so the autocorrector no matter what doesnt work for me i tried restarting downloading nothing happend please help.

**Comment by irockdude554** [comment]
I’m having the same issue as well, seems like it started doing this today.

**Comment by Cronosus** [comment]
well.. then i'm sure its caused by plugin.. some plugins just stopped working, but i not seen any update.. weird

**Comment by sniperwolfortiz** [comment]
If you guys go to the support server a friend of mine made a fixed version of the plugin and i just now posted a pull request for the updated version of the plugin so it can be fixed asap.

**Comment by irockdude554** [comment]
> If you guys go to the support server a friend of mine made a fixed version of the plugin and i just now posted a pull request for the updated version of the plugin so it can be fixed asap.

Where is it posted at in the discord server?

**Comment by l0c4lh057** [comment]
fixed in [this pr](https://github.com/Metalloriff/BetterDiscordPlugins/pull/47), changed version number in [0be0408](https://github.com/Metalloriff/BetterDiscordPlugins/commit/0be0408853afd7ff7e353e628e096a6aac8438e9)
