### ISSUE TITLE
Unread Count Badges not working

### ISSUE THREAD

**Issue by Kirius88** [Metalloriff/BetterDiscordPlugins#52]
Please fix it! Thanks.

**Comment by danrleydfl** [comment]
please

**Comment by botischroeder** [comment]
It's still broken. Please fix it.

**Comment by l0c4lh057** [comment]
![image](https://user-images.githubusercontent.com/42084688/62630886-0da50c80-b930-11e9-85aa-7cf1dac328d4.png)
if i don't have the motivation and metalloriff does not have time to fix it, then it won't happen. i already took a look into the problem, but there where too many changes in discord that i dont know what i need to change to fix it
