### ISSUE TITLE
transitioning background freezing when i click on the add image button

### ISSUE THREAD

**Issue by captainfloofs** [Metalloriff/BetterDiscordPlugins#53]

**Comment by Koishichi** [comment]
sad I have the same problem

**Comment by DarkObscurity** [comment]
Same! :(

**Comment by DarkObscurity** [comment]
It seems like it start to freeze when adding an image when the Pick images at random option is turned on. After disabling it, i could add images.

**Comment by Koishichi** [comment]
thx thats work if I disabling it
