### ISSUE TITLE
DetailedServerTooltips: Wrong member count.

### ISSUE THREAD

**Issue by zeuzi** [Metalloriff/BetterDiscordPlugins#54]
https://imgur.com/a/5sh6iFJ
actual users 139 
tooltip says 217 😂

**Comment by Huddlect** [comment]
I have the same problem, it works with guilds with less than 100 members though.

**Comment by zeuzi** [comment]
> I have the same problem, it works with guilds with less than 100 members though.

Not true one server of mine the tooltip shows 13 users even tho there are only 9 :)

**Comment by Metalloriff** [comment]
I'm not able to recreate this bug. It's always showing correctly for me. Is it still happening?

**Comment by l0c4lh057** [comment]
I think that was when I switched to the member count module which shows the wrong count. But I already changed it, now it is loading the exact member count when the module says there are less than 500 members. But an update would be nice tho

**Comment by l0c4lh057** [comment]
since i did not hear any complaints about this anymore and the member count should only be wrong if there are more than 500 members i am closing this. if this still happens you can comment here and i'll open it again, or you just create a new issue
