### ISSUE TITLE
please, i fucking beg. update SuppressUserMentions.plugin.js

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [Metalloriff/BetterDiscordPlugins#58]
i need it in my life, i used it so much. this poor plugin hasn't been updated in 10 months. its been neglected. FeelsBadMan.

**Comment by Metalloriff** [comment]
It's fixed now, I'm really sorry about that, I wasn't aware that it wasn't working. The fastest way to contact me is through Discord. (Metalloriff
#2891)
