### ISSUE TITLE
User Avatar And Server Icon Viewer - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by agneljills** [Metalloriff/BetterDiscordPlugins#61]
If you right-click to see options on someone at some specific places, it cuts out some important information like the "Copy ID" button. Here is a photo of the bug which might help you understand it better - https://imgur.com/a/KGbVgsN

**Comment by Metalloriff** [comment]
Fixed in the latest update of my lib, not the plugin. This should fix the issue with all plugins, whether they're made by me or not. The context menu should no longer be able to clip out of window. Thank you for reporting it!
