### ISSUE TITLE
VoiceChatNotifications v2.2.3 - Settings Menu Typo

### ISSUE THREAD

**Issue by cdantetho** [Metalloriff/BetterDiscordPlugins#62]
**Details:**
There is a typo in the settings menu of the current release of VoiceChatNotifications.plugin.js (v2.2.3 - Commit e453fc6). Seems to have been an issue since 1.1.3 or prior but I hadn't used the plugin before now.

**Typo:**
Current Title: `"Display notificaitons on user mute/unmute"`
Typo: "notificaitons"
https://github.com/Metalloriff/BetterDiscordPlugins/blob/e89aa14b93084b5de457521551aa135aae2f0b47/VoiceChatNotifications.plugin.js#L77

Suggested New Title: `"Display notifications on user mute/unmute"`
**I'm currently working on a new pull request to fix this issue and adding other small changes.**

**Comment by l0c4lh057** [comment]
got fixed in #63
