### ISSUE TITLE
Suggestion for AutoCorrect.plugin.js

### ISSUE THREAD

**Issue by BrianDaTruth** [Metalloriff/BetterDiscordPlugins#7]
In the Ignored prefixes make : (colon) default so it doesn't try and autocorrect emotes.

Also maybe another option if capitalized then ignore correction.

**Comment by Metalloriff** [comment]
It already doesn't autocorrect emotes. Unless you mean the automatic emotes, like ":)", then that's something I've been meaning to fix.
