### ISSUE TITLE
Message Logger - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by FerretShiny** [Metalloriff/BetterDiscordPlugins#70]
the download link (DownGit) has an error saying "Error server failure or wrong URL."

**Comment by l0c4lh057** [comment]
download from [here](https://github.com/Metalloriff/UnofficialBetterDiscordPlugins/blob/master/MessageLogger.plugin.js)

**Comment by FerretShiny** [comment]
ok thanks
Sincerely


Mr. Spaghetti
