### ISSUE TITLE
Message Logger - Discord Source - [Issue Report] (Download link broken)

### ISSUE THREAD

**Issue by TotallyNotLeet** [Metalloriff/BetterDiscordPlugins#77]
As of 8/1/2019, the download link for this plugin is broken. Also, I tried using it today and it didn't work. Please fix.

**Comment by l0c4lh057** [comment]
download link: https://github.com/Metalloriff/UnofficialBetterDiscordPlugins/blob/master/MessageLogger.plugin.js

broken: reloading it or deleting it's data file (plugins folder -> MessageLoggerData.config.json) should fix it

**Comment by hiideki** [comment]
9/27/2022, it keeps telling me the libs are outdated or something but when i redownload them they cant be read
