### ISSUE TITLE
SendLinksDirectly - Fails to Upload

### ISSUE THREAD

**Issue by McCovican** [Metalloriff/BetterDiscordPlugins#84]
Howdy,

The SendLinksDirectly plugin no longer seems to be functioning at all. Any link sent between brackets will now just disappear into the ether with no action or error occurring - simply as if the message had never been sent. Tried disabling and re-enabling the plugin, as well as restarting Discord etc. etc. Using Discord Stable, win7x64.

**Comment by DokVis** [comment]
Still doesn't work, need it, imgur videos with sound are killing me

**Comment by Arion-Kun** [comment]
Doesnt work, can confirm

**Comment by BuyMyMojo** [comment]
bump for fix?
