### ISSUE TITLE
[Bug] Guild Counter Does not Displays a guild counter below the online friend counter

### ISSUE THREAD

**Issue by Kederan** [Metalloriff/BetterDiscordPlugins#99]
**Which plugin is this about?**
Guild Counter v1.0.4 by Metalloriff

**Describe the Bug**
Does not Displays a guild counter below the online friend counter.

**To Reproduce**
Turned plugin off and on. And refreshed client with same result.

**Expected Behavior**
Displays a guild counter below the online friend counter.

**Screenshots**
![Discord_2019-09-13_20-17-55](https://user-images.githubusercontent.com/19885815/64901127-f01c3e80-d663-11e9-9097-cdd290ec83e9.png)

**Discord Version**
Stable

**Comment by DesertDog1178** [comment]
I am having the same issue
